services:
  - type: web
    name: smart-goal-planner-api
    env: node
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: smart-goal-planner-api
          property: port
